version: '3.7'

services:
  backend:
    build:
      context: ./eisenmann-backend
      dockerfile: Dockerfile.prod
    restart: always
    command: gunicorn eisenmann_inventory_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  # frontend: 
  #   build: 
  #     context: ./eisenmann-frontend
  #     dockerfile: Dockerfile.prod
  #   ports: #This is used to map the container’s ports to the host machine.
  #     - "3000:3000"
  #   env_file:
  #     - ./.env.prod

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1330:80
    depends_on:
      - backend
      # - frontend

volumes:
  postgres_data: null
  static_volume: null
  media_volume: null
