from .entry_serializer import ProductEntrySerializer
from .product_serializer import ProductSerializer, ProductStockSimpleSerializer, ProductDetailedSerializer, ProductStockSerializer, ProductStockRealSerializer
from .entry_serializer import ProductEntrySerializer
