# Generated by Django 3.2.5 on 2022-02-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220202_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstock',
            old_name='medium_value',
            new_name='medium_stock',
        ),
        migrations.RenameField(
            model_name='productstock',
            old_name='minium_value',
            new_name='minium_stock',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='stock_total',
        ),
        migrations.AlterField(
            model_name='productentry',
            name='product_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_entry', to='product.productstock'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_stock', to='product.product'),
        ),
    ]
